/**
 * Curated database of the 45 most common consumer services, with security scores,
 * data handling practices, and EU alternatives.
 *
 * Threat Score methodology:
 *  HIGH   = confirmed data breach with user data exposed, and/or active data selling
 *  MEDIUM = no major breaches but collects/shares significant data, or confirmed metadata leak
 *  LOW    = relatively good track record, limited data collection
 *
 * Data Protection methodology:
 *  HIGH   = strong encryption, GDPR-compliant, minimal data collection
 *  MEDIUM = reasonable practices, but with room for improvement
 *  LOW    = sells user data, limited transparency, outside EU jurisdiction
 */

export type ThreatLevel = "HIGH" | "MEDIUM" | "LOW";

export interface ServiceInfo {
  id: string;
  name: string;
  domain: string;
  /** Category for display and filtering */
  category:
    | "social"
    | "email"
    | "cloud"
    | "streaming"
    | "shopping"
    | "search"
    | "productivity"
    | "communication"
    | "finance"
    | "security"
    | "travel"
    | "tech"
    | "gaming"
    | "dating"
    | "food"
    | "fitness"
    | "education";
  threatScore: ThreatLevel;
  dataProtection: ThreatLevel;
  /** Short facts shown in dashboard row */
  breachSummary: string;
  /** More detailed explanation for expanded view */
  details: string;
  /** Country where the company is registered */
  ownerCountry: string;
  /** Sells or shares data with third parties */
  sellsData: boolean;
  /** URL for deleting account */
  deleteUrl?: string;
  /** URL for changing email address */
  changeEmailUrl?: string;
  /** ID of EU alternative in ALTERNATIVES catalogue */
  euAlternativeId?: string;
  /** Direct affiliate link to recommended alternative */
  affiliateUrl?: string;
}

export const SERVICES: ServiceInfo[] = [
  // ─── SOCIAL ───────────────────────────────────────────────────────────────
  {
    id: "facebook",
    name: "Facebook",
    domain: "facebook.com",
    category: "social",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "533M users leaked (2021), Cambridge Analytica (2018)",
    details:
      "Facebook was exposed in the Cambridge Analytica scandal (2018), where 87 million user profiles were used for political manipulation without consent. In 2021, phone numbers and personal data of 533 million users were published on a hacker forum. Facebook is known for selling ad profiles based on detailed user behaviour.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.facebook.com/help/delete_account",
    changeEmailUrl: "https://www.facebook.com/settings?tab=account",
    euAlternativeId: "mastodon",
  },
  {
    id: "instagram",
    name: "Instagram",
    domain: "instagram.com",
    category: "social",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Owned by Meta, shares data with Facebook",
    details:
      "Instagram is owned by Meta and shares all collected data with Facebook. In 2019, 49 million user profiles were exposed via an unsecured database. Meta was fined €405 million by the Irish DPC (2022) for violating children's privacy on Instagram.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.instagram.com/accounts/remove/request/permanent/",
    changeEmailUrl: "https://www.instagram.com/accounts/edit/",
    euAlternativeId: "pixelfed",
  },
  {
    id: "twitter-x",
    name: "X (Twitter)",
    domain: "x.com",
    category: "social",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "200M email addresses leaked (2022), weakened security culture",
    details:
      "In December 2022, email addresses of over 200 million Twitter users were published on hacker forums. After Elon Musk's acquisition in 2022, much of the security team was fired, and key GDPR compliance staff left the company. The EU has opened an investigation.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://twitter.com/settings/account/confirm_deactivation",
    changeEmailUrl: "https://twitter.com/settings/email",
    euAlternativeId: "mastodon",
  },
  {
    id: "tiktok",
    name: "TikTok",
    domain: "tiktok.com",
    category: "social",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Chinese ownership, EU fines (2023), data transfers to China",
    details:
      "TikTok is owned by ByteDance, headquartered in China. The EU fined TikTok €345 million (2023) for violations of children's privacy. The Irish DPC confirmed that employees in China had access to European user data. TikTok bans have been imposed for staff at EU institutions and several national governments.",
    ownerCountry: "CN",
    sellsData: true,
    deleteUrl: "https://www.tiktok.com/setting/delete-account",
    changeEmailUrl: "https://www.tiktok.com/setting/",
  },
  {
    id: "snapchat",
    name: "Snapchat",
    domain: "snapchat.com",
    category: "social",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "4.6M users exposed (2014), insider data abuse",
    details:
      "In 2014, 4.6 million user phone numbers and usernames were published publicly. Snaplion was a third-party app that stored images that were supposed to disappear. In 2019, it was revealed that Snap employees misused an internal tool (SnapLion) to spy on users.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://accounts.snapchat.com/accounts/delete_account",
    changeEmailUrl: "https://accounts.snapchat.com/accounts/settings",
  },
  {
    id: "reddit",
    name: "Reddit",
    domain: "reddit.com",
    category: "social",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2018 database compromise, API data sold to AI companies",
    details:
      "In 2018, Reddit was hacked via SMS-based 2FA. Reddit now sells API access to AI companies (Google, OpenAI) for user content, which many users protested. Users have thus contributed to training commercial AI models without consent.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.reddit.com/settings/",
    changeEmailUrl: "https://www.reddit.com/settings/",
    euAlternativeId: "lemmy",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    domain: "pinterest.com",
    category: "social",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches – but user data analysed for ads",
    details:
      "Pinterest has not had major public data breaches, but collects detailed information about interests and behaviour for advertising purposes. They are subject to US jurisdiction and share data with advertising partners.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.pinterest.com/settings/",
    changeEmailUrl: "https://www.pinterest.com/settings/",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    domain: "linkedin.com",
    category: "social",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "700M users scraped (2021), 117M passwords leaked (2012/2016)",
    details:
      "In 2012, 6.5 million hashed passwords were leaked — in 2016 it became clear it was actually 117 million. In 2021, data from 700 million LinkedIn profiles was scraped and sold. LinkedIn, owned by Microsoft, uses profile data for advertising purposes.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.linkedin.com/psettings/account",
    changeEmailUrl: "https://www.linkedin.com/psettings/email",
    euAlternativeId: "xing",
  },
  {
    id: "youtube",
    name: "YouTube",
    domain: "youtube.com",
    category: "social",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "Owned by Google, massive behavioural profiling",
    details:
      "YouTube is owned by Google and builds detailed behavioural profiles based on viewing history. Google was fined $170 million (2019) by the FTC for illegally collecting children's data on YouTube. All viewing history is shared with Google Ads.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://myaccount.google.com/deleteaccount",
    changeEmailUrl: "https://myaccount.google.com/email",
    euAlternativeId: "peertube",
  },

  // ─── EMAIL ────────────────────────────────────────────────────────────────
  {
    id: "gmail",
    name: "Gmail",
    domain: "gmail.com",
    category: "email",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "Content scanning for ad profiles, Google data ecosystem",
    details:
      "Google scanned Gmail content for advertising purposes until 2017. Although direct scanning stopped, Google uses metadata and links Gmail activity to ad profiles. All data is subject to US jurisdiction and the CLOUD Act, which gives US authorities access.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://myaccount.google.com/deleteaccount",
    changeEmailUrl: "https://myaccount.google.com/email",
    euAlternativeId: "proton-mail",
    affiliateUrl:
      "https://go.getproton.me/SH2jh?redirect_url=https%3A%2F%2Fget.proton.me%2Fl%2Fmail-plans-aff-intro-offer",
  },
  {
    id: "outlook",
    name: "Outlook / Hotmail",
    domain: "outlook.com",
    category: "email",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Microsoft data sharing, CLOUD Act exposure",
    details:
      "Microsoft Exchange and Outlook were compromised by Hafnium (2021) and Storm-0558 (2023), the latter affecting government email accounts. Microsoft is subject to the CLOUD Act and can hand over data to US authorities without a European court order.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://account.live.com/closeAccount.aspx",
    changeEmailUrl: "https://account.live.com/names/Manage",
    euAlternativeId: "tuta",
  },
  {
    id: "yahoo-mail",
    name: "Yahoo Mail",
    domain: "yahoo.com",
    category: "email",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "3 BILLION accounts leaked (2013–2016)",
    details:
      "Yahoo had the largest data breach in history: 3 billion accounts compromised between 2013 and 2016. In 2016, Yahoo was also compelled by the NSA to mass-surveil user emails. The company was acquired by Verizon and is now part of Apollo Global.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://login.yahoo.com/account/delete-account",
    changeEmailUrl: "https://edit.yahoo.com/config/eval_profile",
    euAlternativeId: "proton-mail",
    affiliateUrl:
      "https://go.getproton.me/SH2jh?redirect_url=https%3A%2F%2Fget.proton.me%2Fl%2Fmail-plans-aff-intro-offer",
  },

  // ─── CLOUD STORAGE ────────────────────────────────────────────────────────
  {
    id: "google-drive",
    name: "Google Drive",
    domain: "drive.google.com",
    category: "cloud",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "Google can read files, US jurisdiction",
    details:
      "Google Drive files are encrypted, but Google holds the keys and can read the content. Google has handed over user data to US authorities via the CLOUD Act. Drive is linked to Google Workspace profiling.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://myaccount.google.com/deleteaccount",
    changeEmailUrl: "https://myaccount.google.com/email",
    euAlternativeId: "proton-drive",
    affiliateUrl:
      "https://go.getproton.me/SH1mO?redirect_url=https%3A%2F%2Fget.proton.me%2Fl%2Fprivate-cloud-storage-aff-intro-offer",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    domain: "dropbox.com",
    category: "cloud",
    threatScore: "HIGH",
    dataProtection: "MEDIUM",
    breachSummary: "68M passwords leaked (2012), disclosed in 2016",
    details:
      "In 2012, 68 million Dropbox accounts were compromised, but it was not publicly disclosed until 2016. Dropbox received criticism for offering Condoleezza Rice (board member with NSA ties) a seat on its board. Files are encrypted, but Dropbox holds the keys.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://www.dropbox.com/account/delete_account_email",
    changeEmailUrl: "https://www.dropbox.com/account/personal#email",
    euAlternativeId: "proton-drive",
    affiliateUrl:
      "https://go.getproton.me/SH1mO?redirect_url=https%3A%2F%2Fget.proton.me%2Fl%2Fprivate-cloud-storage-aff-intro-offer",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    domain: "onedrive.com",
    category: "cloud",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Microsoft Storm-0558 (2023), CLOUD Act",
    details:
      "Microsoft was hit by the Storm-0558 attack (2023) where Chinese hackers gained access to emails and cloud documents at government customers. OneDrive is subject to the CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://account.microsoft.com/account/",
    changeEmailUrl: "https://account.live.com/names/Manage",
    euAlternativeId: "proton-drive",
    affiliateUrl:
      "https://go.getproton.me/SH1mO?redirect_url=https%3A%2F%2Fget.proton.me%2Fl%2Fprivate-cloud-storage-aff-intro-offer",
  },
  {
    id: "icloud",
    name: "iCloud",
    domain: "icloud.com",
    category: "cloud",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "The Fappening (2014), Apple/China server compromise",
    details:
      "In 2014, celebrity photos were leaked from iCloud via phishing and brute force (The Fappening). Apple stores Chinese user data on servers in China owned by state-controlled GCBD, giving Chinese authorities access. Apple is subject to the US CLOUD Act for other regions.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://appleid.apple.com/account/manage",
    changeEmailUrl: "https://appleid.apple.com/account/manage",
    euAlternativeId: "proton-drive",
    affiliateUrl:
      "https://go.getproton.me/SH1mO?redirect_url=https%3A%2F%2Fget.proton.me%2Fl%2Fprivate-cloud-storage-aff-intro-offer",
  },

  // ─── STREAMING ────────────────────────────────────────────────────────────
  {
    id: "netflix",
    name: "Netflix",
    domain: "netflix.com",
    category: "streaming",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches – but detailed behavioural profiling",
    details:
      "Netflix has not had major data breaches, but builds extremely detailed behavioural profiles: what you watch, when you pause, what you skip. These are used for content recommendations and partially shared with advertising partners (ad tier).",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://www.netflix.com/cancelplan",
    changeEmailUrl: "https://www.netflix.com/youraccount",
  },
  {
    id: "spotify",
    name: "Spotify",
    domain: "spotify.com",
    category: "streaming",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches – but voice and audio data collected",
    details:
      "Spotify collects your voice recordings (via microphone access) and places you in advertising profiles. They share data with Facebook if you have linked the accounts. However, Spotify is a Swedish company subject to EU/GDPR.",
    ownerCountry: "SE",
    sellsData: true,
    deleteUrl: "https://support.spotify.com/article/close-account/",
    changeEmailUrl: "https://www.spotify.com/account/overview/",
  },
  {
    id: "disney-plus",
    name: "Disney+",
    domain: "disneyplus.com",
    category: "streaming",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Thousands of accounts sold after compromise (2019)",
    details:
      "Hours after Disney+ launched in 2019, thousands of accounts were hacked and sold on the dark web. Disney shared user data with advertising partners without adequate consent, resulting in a lawsuit in California.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.disneyplus.com/account",
    changeEmailUrl: "https://www.disneyplus.com/account",
  },

  // ─── SHOPPING ─────────────────────────────────────────────────────────────
  {
    id: "amazon",
    name: "Amazon",
    domain: "amazon.com",
    category: "shopping",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "Internal data leak (2018), Alexa eavesdropping, AWS breaches",
    details:
      "In 2018, an Amazon employee leaked customer data to third-party vendors. Alexa voice recordings have been listened to by human employees without users' knowledge. AWS has been involved in several high-profile data breaches at customer organisations.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.amazon.com/gp/help/customer/display.html?nodeId=GDK92DNLSGWTV6MP",
    changeEmailUrl: "https://www.amazon.com/gp/customer-media/upload.html",
  },
  {
    id: "hotels-com",
    name: "Hotels.com",
    domain: "hotels.com",
    category: "travel",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Expedia Group breach, Marriott breach (500M guests)",
    details:
      "Hotels.com is owned by Expedia Group. The Marriott breach (2018) exposed 500 million guest records including passport information — one of the largest in history. Hotels.com shares booking data with advertising networks. The Expedia Group has received a GDPR fine.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.hotels.com/account/",
    changeEmailUrl: "https://www.hotels.com/account/",
    euAlternativeId: "booking-nl",
  },
  {
    id: "booking-com",
    name: "Booking.com",
    domain: "booking.com",
    category: "travel",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Phishing campaign targeted hotels (2024)",
    details:
      "In 2024, many Booking.com hotels were targeted by phishing that gave hackers access to hotel systems and customer communications. Booking is owned by Dutch Booking Holdings but shares data with advertising partners globally.",
    ownerCountry: "NL",
    sellsData: true,
    deleteUrl: "https://account.booking.com/mysettings/",
    changeEmailUrl: "https://account.booking.com/mysettings/",
  },
  {
    id: "airbnb",
    name: "Airbnb",
    domain: "airbnb.com",
    category: "travel",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches – but biometric ID collection",
    details:
      "Airbnb in many cases requires biometric ID verification. They collect and store identity documents. Airbnb shares data with hosts and advertising partners. No major data breaches documented, but ID storage is a privacy concern.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://www.airbnb.com/help/article/186",
    changeEmailUrl: "https://www.airbnb.com/account-settings",
    euAlternativeId: "holidu",
  },
  {
    id: "ebay",
    name: "eBay",
    domain: "ebay.com",
    category: "shopping",
    threatScore: "HIGH",
    dataProtection: "MEDIUM",
    breachSummary: "145M users exposed (2014)",
    details:
      "In 2014, eBay was hacked and data from 145 million users was exposed, including encrypted passwords, names, addresses and dates of birth. eBay waited two months before notifying users. They are now part of a larger data-sharing network.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.ebay.com/help/account/articles/closing-account",
    changeEmailUrl: "https://accountsettings.ebay.com/",
  },

  // ─── SEARCH ───────────────────────────────────────────────────────────────
  {
    id: "google-search",
    name: "Google Search",
    domain: "google.com",
    category: "search",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "Massive search profiling, EU fine €8.25bn",
    details:
      "Google was fined €8.25 billion by the EU (2017–2019) for abuse of its dominant market position via search. Google builds detailed profiles based on search history, linked to your ad profile across all Google services.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://myaccount.google.com/deleteaccount",
    changeEmailUrl: "https://myaccount.google.com/email",
    euAlternativeId: "ecosia",
  },
  {
    id: "bing",
    name: "Bing",
    domain: "bing.com",
    category: "search",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "Microsoft data sharing, CLOUD Act exposure",
    details:
      "Bing is Microsoft's search engine. In 2023, Microsoft was found to have exposed 38 terabytes of internal data through a misconfiguration. Search data is used for Microsoft Advertising.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://account.microsoft.com/account/",
    changeEmailUrl: "https://account.microsoft.com/account/",
    euAlternativeId: "qwant",
  },

  // ─── PRODUCTIVITY ─────────────────────────────────────────────────────────
  {
    id: "google-docs",
    name: "Google Docs / Workspace",
    domain: "docs.google.com",
    category: "productivity",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "Google can read documents, US jurisdiction",
    details:
      "Google Workspace documents are not end-to-end encrypted. Google can read the content and has done so at the request of US authorities. Business data is subject to the CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://myaccount.google.com/deleteaccount",
    changeEmailUrl: "https://myaccount.google.com/email",
    euAlternativeId: "nextcloud",
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    domain: "microsoft.com",
    category: "productivity",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Storm-0558 (2023), government data exposed",
    details:
      "Storm-0558 (Chinese hackers) gained access in 2023 to emails at US government agencies via Microsoft. Microsoft 365 uses metadata to improve AI services. Subject to the CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://account.microsoft.com/account/",
    changeEmailUrl: "https://account.live.com/names/Manage",
    euAlternativeId: "nextcloud",
  },

  // ─── COMMUNICATION ────────────────────────────────────────────────────────
  {
    id: "whatsapp",
    name: "WhatsApp",
    domain: "whatsapp.com",
    category: "communication",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "500M users exposed (2022), Meta data sharing",
    details:
      "In 2022, metadata from 500 million WhatsApp users was put up for sale. Messages are end-to-end encrypted, but metadata (who you talk to, how often, your location) is shared with Meta/Facebook for advertising purposes. WhatsApp in the EU received a €225 million GDPR fine (2021).",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://faq.whatsapp.com/general/account-and-profile/how-to-delete-your-account/",
    changeEmailUrl: "https://faq.whatsapp.com/",
    euAlternativeId: "threema",
  },
  {
    id: "discord",
    name: "Discord",
    domain: "discord.com",
    category: "communication",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Spoonbot breach (2023), content moderator exposure",
    details:
      "A Discord bot platform (Spoonbot) was hacked in 2023, exposing 760 million messages. Discord stores all messages on its servers (not E2E encrypted), and employees have access to message content for moderation.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://support.discord.com/hc/en-us/articles/212500837",
    changeEmailUrl: "https://discord.com/settings/account",
    euAlternativeId: "element-matrix",
  },
  {
    id: "zoom",
    name: "Zoom",
    domain: "zoom.us",
    category: "communication",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "500K accounts sold (2020), Zoomboming period",
    details:
      "In 2020, 500,000 Zoom accounts were sold on the dark web. Zoom was criticised for routing European calls through Chinese servers. Zoom was also fined by the FTC (2020) for lying about end-to-end encryption.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://support.zoom.us/hc/en-us/articles/201363243",
    changeEmailUrl: "https://zoom.us/profile",
    euAlternativeId: "jitsi-meet",
  },
  {
    id: "slack",
    name: "Slack",
    domain: "slack.com",
    category: "communication",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Breach with password leak (2015), Salesforce ownership",
    details:
      "In 2015, Slack was hacked and user profile data including hashed passwords was exposed. Slack is used by Salesforce for AI training. Employer messages are accessible to administrators, and Slack employees can access content when needed.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://slack.com/help/articles/203953148",
    changeEmailUrl: "https://slack.com/help/articles/207262907",
    euAlternativeId: "element-matrix",
  },
  {
    id: "telegram",
    name: "Telegram",
    domain: "telegram.org",
    category: "communication",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Not E2E encrypted by default, Pavel Durov arrested (2024)",
    details:
      "Telegram's regular chats are NOT end-to-end encrypted — only Secret Chats are. Pavel Durov was arrested in France (2024) for failing to cooperate with authorities on content control. Telegram subsequently shared user data with authorities.",
    ownerCountry: "AE",
    sellsData: false,
    deleteUrl: "https://my.telegram.org/",
    changeEmailUrl: "https://my.telegram.org/",
    euAlternativeId: "threema",
  },

  // ─── PASSWORD MANAGERS ────────────────────────────────────────────────────
  {
    id: "lastpass",
    name: "LastPass",
    domain: "lastpass.com",
    category: "security",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Entire vault database stolen (2022) – passwords at risk",
    details:
      "In August and December 2022, LastPass was hacked. Attackers stole encrypted vault data for all users. With weak master passwords, all stored passwords can be decrypted. Millions of users are advised to change all their passwords immediately. LastPass initially lied about the extent of the breach.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://lastpass.com/my.php",
    changeEmailUrl: "https://lastpass.com/my.php",
    euAlternativeId: "proton-pass",
    affiliateUrl:
      "https://go.getproton.me/SH1mP?redirect_url=https%3A%2F%2Fproton.me%2Fl%2Fpass%2Fshorter-flow-pricing",
  },
  {
    id: "1password",
    name: "1Password",
    domain: "1password.com",
    category: "security",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "Okta breach affected internal IT (2023) – no user vaults",
    details:
      "1Password had an incident in 2023 related to the Okta breach where an attacker gained access to IT systems, but no user vaults were compromised. 1Password uses zero-knowledge encryption where they cannot read your passwords.",
    ownerCountry: "CA",
    sellsData: false,
    deleteUrl: "https://support.1password.com/delete-account/",
    changeEmailUrl: "https://my.1password.com/profile",
    euAlternativeId: "proton-pass",
    affiliateUrl:
      "https://go.getproton.me/SH1mP?redirect_url=https%3A%2F%2Fproton.me%2Fl%2Fpass%2Fshorter-flow-pricing",
  },

  // ─── FINANCE ──────────────────────────────────────────────────────────────
  {
    id: "paypal",
    name: "PayPal",
    domain: "paypal.com",
    category: "finance",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "35K accounts credential-stuffed (2023)",
    details:
      "In 2023, 35,000 PayPal accounts were compromised via credential stuffing (reuse of passwords from other leaks). PayPal shares transaction information with advertising partners and has been criticised for broad data-sharing clauses.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.paypal.com/myaccount/closeAccount/",
    changeEmailUrl: "https://www.paypal.com/myaccount/settings/",
    euAlternativeId: "adyen-mollie",
  },

  // ─── TECH / DEV ───────────────────────────────────────────────────────────
  {
    id: "github",
    name: "GitHub",
    domain: "github.com",
    category: "tech",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "Owned by Microsoft, Copilot trains on code without consent",
    details:
      "GitHub is owned by Microsoft. GitHub Copilot was trained on public code without explicit consent from developers, resulting in a lawsuit. Microsoft/GitHub is subject to the CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://github.com/settings/admin",
    changeEmailUrl: "https://github.com/settings/emails",
    euAlternativeId: "codeberg",
  },
  {
    id: "adobe",
    name: "Adobe (CC/Acrobat)",
    domain: "adobe.com",
    category: "tech",
    threatScore: "HIGH",
    dataProtection: "MEDIUM",
    breachSummary: "153M accounts leaked (2013), AI training controversy (2024)",
    details:
      "In 2013, 153 million Adobe accounts were compromised including encrypted passwords and payment information. In 2024, Adobe updated its terms of service to give itself the right to use user content for AI training, which caused significant backlash and contract cancellations.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://account.adobe.com/",
    changeEmailUrl: "https://account.adobe.com/",
    euAlternativeId: "penpot",
  },
  {
    id: "twitch",
    name: "Twitch",
    domain: "twitch.tv",
    category: "streaming",
    threatScore: "HIGH",
    dataProtection: "MEDIUM",
    breachSummary: "Entire platform source code leaked (2021), Amazon ownership",
    details:
      "In 2021, Twitch was hacked and the entire source code, streamer payout data and internal tools were published. Twitch is owned by Amazon. Amazon uses data across its services for advertising purposes.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://www.twitch.tv/settings/profile",
    changeEmailUrl: "https://www.twitch.tv/settings/profile",
    euAlternativeId: "peertube",
  },

  // ─── VPN ──────────────────────────────────────────────────────────────────
  {
    id: "nordvpn",
    name: "NordVPN",
    domain: "nordvpn.com",
    category: "security",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "One server hacked (2018), disclosed in 2019",
    details:
      "One of NordVPN's servers in Finland was compromised in 2018 via an unsecured remote management system. NordVPN did not publicly disclose this until 2019. NordVPN is registered in Panama but operated from Lithuania.",
    ownerCountry: "PA",
    sellsData: false,
    deleteUrl: "https://my.nordaccount.com/dashboard/",
    changeEmailUrl: "https://my.nordaccount.com/dashboard/",
    euAlternativeId: "proton-vpn",
    affiliateUrl:
      "https://go.getproton.me/SH1mQ?redirect_url=https%3A%2F%2Fget.protonvpn.com%2Fl%2Fspecial-partner-offer-summerdeal",
  },
  {
    id: "expressvpn",
    name: "ExpressVPN",
    domain: "expressvpn.com",
    category: "security",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Acquired by Kape (Israeli surveillance experts, 2021)",
    details:
      "ExpressVPN was acquired in 2021 by Kape Technologies (formerly Crossrider), a company with ties to adware and Israeli surveillance specialists. One executive was charged in 2022 for having helped UAE authorities surveil dissidents.",
    ownerCountry: "BVI",
    sellsData: true,
    deleteUrl: "https://www.expressvpn.com/support/",
    changeEmailUrl: "https://www.expressvpn.com/support/",
    euAlternativeId: "proton-vpn",
    affiliateUrl:
      "https://go.getproton.me/SH1mQ?redirect_url=https%3A%2F%2Fget.protonvpn.com%2Fl%2Fspecial-partner-offer-summerdeal",
  },

  // ─── OTHER ────────────────────────────────────────────────────────────────
  {
    id: "uber",
    name: "Uber",
    domain: "uber.com",
    category: "tech",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "57M users leaked (2016), Uber concealed breach for 1 year",
    details:
      "In 2016, 57 million Uber users and drivers were compromised. Uber chose to pay the hackers $100,000 to delete the data and stay silent — and concealed the breach from the public for over a year. Uber was fined $148 million. Competitor Lyft reported its breach within 72 hours as required by GDPR.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://help.uber.com/driving-and-delivering/article/delete-your-uber-account",
    changeEmailUrl: "https://account.uber.com/",
    euAlternativeId: "bolt",
  },
  {
    id: "twitter-ads",
    name: "Google Ads / AdSense",
    domain: "google.com",
    category: "tech",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "Pervasive cross-site tracking",
    details:
      "Google's ad network tracks you across millions of websites via cookies, fingerprinting and conversion tracking. The European Commission has launched multiple antitrust investigations against Google Ads.",
    ownerCountry: "US",
    sellsData: true,
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    domain: "cloudflare.com",
    category: "tech",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "Cloudbleed (2017) – memory leak in middleware",
    details:
      "In 2017, Cloudflare had a memory leak (Cloudbleed) that exposed sensitive data from websites using the service, including passwords and tokens. Cloudflare fixed this quickly and is generally considered a responsible actor.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "bunny-cdn",
  },
  {
    id: "microsoft-account",
    name: "Microsoft Account",
    domain: "microsoft.com",
    category: "productivity",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Storm-0558 (2023), CLOUD Act",
    details:
      "The Microsoft account is the core of Microsoft services. Subject to the CLOUD Act. The Storm-0558 attack (2023) compromised email accounts of senior US government officials via forged authentication tokens.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://account.microsoft.com/account/",
    changeEmailUrl: "https://account.live.com/names/Manage",
  },

  // ─── CRYPTO / TRADING ─────────────────────────────────────────────────────
  {
    id: "kraken",
    name: "Kraken",
    domain: "kraken.com",
    category: "finance",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "No major public breaches, but a target for phishing.",
    details:
      "Kraken is a major US-based cryptocurrency exchange. While it has a decent security track record, user accounts are frequent targets of phishing and social engineering attacks. Data is subject to US jurisdiction.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "bitpanda",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    domain: "coinbase.com",
    category: "finance",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Credential stuffing attack affected 6,000 users (2021).",
    details:
      "In 2021, at least 6,000 Coinbase customers had funds stolen from their accounts after falling victim to a phishing campaign that bypassed SMS-based multi-factor authentication. Coinbase is a publicly-traded US company.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "bitpanda",
  },
  {
    id: "nexo",
    name: "Nexo",
    domain: "nexo.io",
    category: "finance",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major public breaches reported.",
    details:
      "Nexo is a platform for lending and borrowing against crypto assets. It has not suffered major public security breaches, but operates in a complex regulatory environment. Registered in Switzerland, but with global operations.",
    ownerCountry: "CH",
    sellsData: false,
  },
  {
    id: "bitmex",
    name: "BitMEX",
    domain: "bitmex.com",
    category: "finance",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "User email addresses leaked (2019).",
    details:
      "In 2019, BitMEX accidentally leaked a large number of its users' email addresses by using the 'To' field instead of 'Bcc' in a mass email. The platform has also faced regulatory scrutiny in several countries.",
    ownerCountry: "SC", // Seychelles
    sellsData: false,
    euAlternativeId: "bitpanda",
  },
  {
    id: "tradingview",
    name: "TradingView",
    domain: "tradingview.com",
    category: "finance",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major public breaches reported.",
    details:
      "TradingView is a popular charting and social networking platform for traders. It has a good security record but collects user data for analytics and personalisation. It's a US-based company.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "unstoppable-domains",
    name: "Unstoppable Domains",
    domain: "unstoppabledomains.com",
    category: "tech",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major public breaches reported.",
    details:
      "Provides blockchain-based domain names. As a decentralised service, the security model is different, but the central company is based in the US.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "moonpay",
    name: "MoonPay",
    domain: "moonpay.com",
    category: "finance",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches, but processes sensitive payment data.",
    details:
      "MoonPay is a financial technology company that builds payments infrastructure for crypto. It handles sensitive user and payment information, making it a high-value target.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "crypto-com",
    name: "Crypto.com",
    domain: "crypto.com",
    category: "finance",
    threatScore: "HIGH",
    dataProtection: "MEDIUM",
    breachSummary: "Unauthorised withdrawals of $34M (2022).",
    details:
      "In January 2022, Crypto.com was hacked, leading to unauthorised withdrawals of about $15 million in ETH and $19 million in BTC from 483 user accounts. The company reimbursed the users.",
    ownerCountry: "SG", // Singapore
    sellsData: false,
    euAlternativeId: "bitpanda",
  },
  {
    id: "okx",
    name: "OKX",
    domain: "okx.com",
    category: "finance",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Users targeted by sophisticated social engineering.",
    details:
      "OKX is a global cryptocurrency exchange. While the platform itself has not reported major breaches, its users are frequently targeted by advanced phishing and social engineering attacks.",
    ownerCountry: "SC", // Seychelles
    sellsData: false,
    euAlternativeId: "bitpanda",
  },
  {
    id: "bybit",
    name: "Bybit",
    domain: "bybit.com",
    category: "finance",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "No major public breaches reported.",
    details:
      "Bybit is a cryptocurrency derivatives exchange. It has avoided major public hacks but operates in a high-risk sector and has faced regulatory warnings in some jurisdictions.",
    ownerCountry: "AE", // UAE (Dubai)
    sellsData: false,
    euAlternativeId: "bitpanda",
  },

  // ─── TRAVEL / LIFESTYLE ───────────────────────────────────────────────────
  {
    id: "lime",
    name: "Lime",
    domain: "li.me",
    category: "travel",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "Collects location and travel data.",
    details:
      "Lime, the scooter and bike rental service, collects detailed location and travel history data. While not breached, this data provides a comprehensive picture of user movements. US-based company.",
    ownerCountry: "US",
    sellsData: true,
    euAlternativeId: "tier",
  },
  {
    id: "finn",
    name: "FINN.no",
    domain: "finn.no",
    category: "shopping",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches, owned by Schibsted (NO).",
    details:
      "FINN.no is Norway's largest online marketplace. Owned by Schibsted, it is subject to Norwegian law and GDPR. It has a strong security record.",
    ownerCountry: "NO",
    sellsData: false,
    euAlternativeId: "finn-no",
  },

  // ─── DEV / HOSTING ────────────────────────────────────────────────────────
  {
    id: "supabase",
    name: "Supabase",
    domain: "supabase.com",
    category: "tech",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches, but holds sensitive developer data.",
    details:
      "Supabase provides a backend-as-a-service platform. While it has a good security reputation, it holds potentially sensitive data and API keys for many applications. US-based company.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "netlify",
    name: "Netlify",
    domain: "netlify.com",
    category: "tech",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches, but a critical part of web infrastructure.",
    details:
      "Netlify is a popular platform for hosting modern web applications. It has a strong security focus but is a high-value target due to its central role for many businesses. US-based.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "scaleway",
  },
  {
    id: "vercel",
    name: "Vercel",
    domain: "vercel.com",
    category: "tech",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches, hosts critical web applications.",
    details:
      "Vercel, the company behind Next.js, is a leading platform for frontend development and hosting. Like Netlify, it's a critical infrastructure provider with a strong security posture. US-based.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "scaleway",
  },
  {
    id: "sentry",
    name: "Sentry",
    domain: "sentry.io",
    category: "tech",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches, but processes application error data.",
    details:
      "Sentry is an error tracking platform that can process potentially sensitive user data from applications. It has a good security record. US-based.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "namecheap",
    name: "Namecheap",
    domain: "namecheap.com",
    category: "tech",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Third-party email provider breached (2023), leading to phishing.",
    details:
      "In February 2023, Namecheap's third-party email system was compromised, leading to phishing emails being sent to its customers. The core domain registration system was not affected. US-based.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "ionos",
  },
  {
    id: "godaddy",
    name: "GoDaddy",
    domain: "godaddy.com",
    category: "tech",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Multiple breaches over several years (2020-2023).",
    details:
      "GoDaddy has suffered a series of breaches. In 2020, 28,000 hosting accounts were compromised. In 2021, 1.2 million WordPress customers had data exposed. In 2023, they revealed a multi-year breach where malware was installed on their servers.",
    ownerCountry: "US",
    sellsData: true,
    euAlternativeId: "ionos",
  },
  {
    id: "replit",
    name: "Replit",
    domain: "replit.com",
    category: "tech",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major public breaches reported.",
    details:
      "Replit is an online IDE. It has a good security track record but hosts user code and secrets, making it a potential target. US-based.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "gitpod",
  },
  {
    id: "hugging-face",
    name: "Hugging Face",
    domain: "huggingface.co",
    category: "tech",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "API tokens for Spaces secrets were compromised (2024).",
    details:
      "In April 2024, Hugging Face detected a security incident where unauthorised users gained access to secrets within their Spaces platform, potentially exposing API tokens and other credentials.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "aws",
    name: "AWS",
    domain: "aws.amazon.com",
    category: "tech",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Customer misconfigurations are a major source of leaks.",
    details:
      "While AWS itself is generally secure, misconfigured S3 buckets and other services by customers have led to countless data breaches. AWS is owned by Amazon and subject to the US CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "hetzner-online",
  },

  // --- Gaming ---
  {
    id: "steam",
    name: "Steam",
    domain: "store.steampowered.com",
    category: "gaming",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2011 breach exposed 35M accounts including encrypted passwords.",
    details:
      "Steam (Valve) suffered a major breach in 2011 exposing usernames, hashed passwords, and credit card data. Steam collects extensive playtime, purchase, and behavioural data. Subject to US CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://help.steampowered.com/en/wizard/HelpDeleteAccount",
    euAlternativeId: "gog",
  },
  {
    id: "epic-games",
    name: "Epic Games",
    domain: "epicgames.com",
    category: "gaming",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "2019 breach affected millions; Fortnite accounts repeatedly targeted.",
    details:
      "Epic Games was subject to a major credential-stuffing campaign in 2019 compromising millions of Fortnite accounts. The company also faced FTC action for deceptive practices targeting minors and collecting children's data.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://www.epicgames.com/help/en-US/c-Category_TechnicalSupport/c-TechnicalSupport_AccountSupport/how-do-i-delete-my-epic-games-account-a000084416",
    euAlternativeId: "gog",
  },
  {
    id: "playstation",
    name: "PlayStation Network",
    domain: "playstation.com",
    category: "gaming",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2011 breach exposed 77M accounts; 2023 Insomniac Games hack leaked data.",
    details:
      "The 2011 PlayStation Network outage and breach is one of the largest in history, exposing names, addresses, email, birth dates, and encrypted credit card data for 77 million users. Sony has faced repeated security incidents.",
    ownerCountry: "JP",
    sellsData: false,
    deleteUrl: "https://www.playstation.com/en-us/support/account/delete-psn-account/",
  },
  {
    id: "xbox",
    name: "Xbox / Microsoft",
    domain: "xbox.com",
    category: "gaming",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Microsoft breaches in 2021 and 2023 exposed customer email and data.",
    details:
      "Microsoft (Xbox parent) suffered significant breaches in 2021 (Exchange Server) and 2023 (Storm-0558 group accessed email accounts). Xbox collects detailed playtime, purchase, and social graph data. Subject to US CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "nintendo",
    name: "Nintendo",
    domain: "nintendo.com",
    category: "gaming",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2020 breach exposed 160,000 Nintendo Network IDs.",
    details:
      "In 2020, attackers accessed approximately 160,000 Nintendo Network accounts through credential stuffing. Nintendo collects gaming data and purchase history, but is generally considered less invasive than US platforms.",
    ownerCountry: "JP",
    sellsData: false,
    deleteUrl: "https://accounts.nintendo.com/profile/deleteaccount",
  },
  {
    id: "roblox",
    name: "Roblox",
    domain: "roblox.com",
    category: "gaming",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Targeted at children; confidential data leaked in 2022.",
    details:
      "Roblox's primary audience is children. In 2022, a hacker published confidential documents including user data, content moderation records, and personal details. The platform has faced criticism over child safety and data practices.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://en.help.roblox.com/hc/en-us/articles/203312560",
  },
  {
    id: "battlenet",
    name: "Battle.net",
    domain: "battle.net",
    category: "gaming",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2012 breach exposed email addresses and security question answers.",
    details:
      "Blizzard's Battle.net platform suffered a breach in 2012 exposing email addresses and hashed security answers. Blizzard is owned by Activision Blizzard (now Microsoft) and subject to the US CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "riot-games",
    name: "Riot Games / League of Legends",
    domain: "riotgames.com",
    category: "gaming",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2023 source code stolen; anti-cheat systems compromised.",
    details:
      "In 2023, Riot Games was targeted by ransomware attackers who stole source code for League of Legends, Teamfight Tactics, and an anti-cheat tool. Riot is a subsidiary of Tencent, the Chinese tech giant, raising additional data sovereignty concerns.",
    ownerCountry: "CN",
    sellsData: false,
  },
  {
    id: "ea",
    name: "EA (Electronic Arts)",
    domain: "ea.com",
    category: "gaming",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2021 breach: source code for FIFA 21 and Frostbite engine stolen.",
    details:
      "In 2021, hackers stole 780 GB of source code from EA including FIFA 21 and the Frostbite engine. EA collects extensive data on gaming behaviour and links accounts to real identities for purchase history.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://help.ea.com/en/help/account/close-your-ea-account/",
  },
  {
    id: "gog",
    name: "GOG",
    domain: "gog.com",
    category: "gaming",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches reported. DRM-free gaming platform.",
    details:
      "GOG (Good Old Games) is owned by CD Projekt (Poland) and offers DRM-free game downloads. No major data breaches have been reported. Being EU-based (Poland) it is subject to GDPR.",
    ownerCountry: "PL",
    sellsData: false,
    euAlternativeId: "gog",
  },

  // --- Dating ---
  {
    id: "tinder",
    name: "Tinder",
    domain: "tinder.com",
    category: "dating",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2020: 70,000 images scraped; extensive location and personal data collected.",
    details:
      "Tinder (owned by Match Group, US) collects highly sensitive data including location, sexual preferences, and private messages. In 2020, 70,000 women's photos were scraped without consent. Security researchers have repeatedly highlighted location-tracking vulnerabilities.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://account.gotinder.com/delete",
    euAlternativeId: "happn",
  },
  {
    id: "bumble",
    name: "Bumble",
    domain: "bumble.com",
    category: "dating",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2021: API flaw exposed precise user locations.",
    details:
      "In 2021 security researchers discovered an API vulnerability in Bumble that could expose users' precise locations. Bumble is US-headquartered and collects extensive personal and location data.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://bumble.com/en-us/help/how-do-i-delete-my-account",
    euAlternativeId: "happn",
  },
  {
    id: "grindr",
    name: "Grindr",
    domain: "grindr.com",
    category: "dating",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Sold HIV status and precise location data to third parties.",
    details:
      "Grindr sold users' HIV status and precise GPS location to third-party advertisers until 2018 when the practice was exposed. The app was previously owned by a Chinese company (Kunlun Tech) and was forced to divest. Collects highly sensitive data on sexual orientation.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://help.grindr.com/hc/en-us/articles/360000291573",
  },
  {
    id: "hinge",
    name: "Hinge",
    domain: "hinge.co",
    category: "dating",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches; owned by Match Group which has security issues.",
    details:
      "Hinge is owned by Match Group (US) and collects extensive personal and preference data. While Hinge itself has not had major breaches, its parent company Match Group has faced multiple security and privacy issues.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://hinge.co/help/articles/delete-account",
    euAlternativeId: "happn",
  },
  {
    id: "badoo",
    name: "Badoo",
    domain: "badoo.com",
    category: "dating",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2013 breach exposed 112M records; re-leaked in 2020.",
    details:
      "Badoo suffered a significant breach in 2013 with records of approximately 112 million users later re-leaked in 2020. Headquartered in Cyprus (EU jurisdiction) but with significant Russian leadership history.",
    ownerCountry: "CY",
    sellsData: false,
  },
  {
    id: "meetic",
    name: "Meetic",
    domain: "meetic.com",
    category: "dating",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "No major independent breaches; part of Match Group.",
    details:
      "Meetic is a European dating service owned by Match Group (US). Being EU-registered gives it GDPR exposure, but ultimate data control lies with the US parent company.",
    ownerCountry: "FR",
    sellsData: false,
  },

  // --- Food & Delivery ---
  {
    id: "uber-eats",
    name: "Uber Eats",
    domain: "ubereats.com",
    category: "food",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2022 Uber breach exposed driver and customer data.",
    details:
      "Uber suffered a major breach in 2022 where an attacker gained full access to internal systems including Slack, HackerOne reports, and employee data. Uber Eats collects detailed location, payment, and purchase history data.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://help.uber.com/riders/article/delete-your-uber-account",
    euAlternativeId: "wolt",
  },
  {
    id: "deliveroo",
    name: "Deliveroo",
    domain: "deliveroo.com",
    category: "food",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Targeted by credential stuffing in 2016; ongoing account takeovers.",
    details:
      "Deliveroo has experienced repeated credential-stuffing attacks since 2016. UK-registered (post-Brexit, no GDPR), it collects location, payment, and ordering data. Owned by Amazon since 2021.",
    ownerCountry: "GB",
    sellsData: false,
    deleteUrl: "https://help.deliveroo.com/en/articles/2536036-delete-your-account",
    euAlternativeId: "wolt",
  },
  {
    id: "just-eat",
    name: "Just Eat Takeaway",
    domain: "justeattakeaway.com",
    category: "food",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Multiple account takeover reports; Dutch parent company.",
    details:
      "Just Eat Takeaway is headquartered in the Netherlands (GDPR jurisdiction) and collects order history, location, and payment data. There have been recurring reports of account takeovers via credential stuffing.",
    ownerCountry: "NL",
    sellsData: false,
    euAlternativeId: "just-eat",
  },
  {
    id: "wolt",
    name: "Wolt",
    domain: "wolt.com",
    category: "food",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No significant breaches reported. Finnish company.",
    details:
      "Wolt is a Finnish food delivery company (now owned by DoorDash, US) with good GDPR compliance practices. No significant data breaches have been reported. The US acquisition by DoorDash is a concern for data sovereignty.",
    ownerCountry: "FI",
    sellsData: false,
    euAlternativeId: "wolt",
  },
  {
    id: "hellofresh",
    name: "HelloFresh",
    domain: "hellofresh.com",
    category: "food",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches. German meal-kit company.",
    details:
      "HelloFresh is a German-listed company (Berlin HQ) subject to GDPR. No significant data breaches reported. Collects delivery address, dietary preferences, and payment data.",
    ownerCountry: "DE",
    sellsData: false,
    euAlternativeId: "hellofresh",
    deleteUrl: "https://www.hellofresh.com/account/unsubscribe",
  },

  // --- Finance & Fintech ---
  {
    id: "revolut",
    name: "Revolut",
    domain: "revolut.com",
    category: "finance",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2022 breach exposed personal data of 50,150 customers.",
    details:
      "In September 2022, a social engineering attack on a Revolut employee led to unauthorised access to data for 50,150 customers, including names, partial card numbers, and addresses. UK and Lithuanian-regulated fintech.",
    ownerCountry: "GB",
    sellsData: false,
    deleteUrl: "https://www.revolut.com/legal/privacy/",
    euAlternativeId: "n26",
  },
  {
    id: "n26",
    name: "N26",
    domain: "n26.com",
    category: "finance",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches. German-licensed bank under strict EU regulation.",
    details:
      "N26 is a German-licensed bank regulated by BaFin (Germany) and the ECB, fully GDPR-compliant. No significant data breaches reported. Full EU banking licence with deposit protection up to €100,000.",
    ownerCountry: "DE",
    sellsData: false,
    euAlternativeId: "n26",
  },
  {
    id: "wise",
    name: "Wise",
    domain: "wise.com",
    category: "finance",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "2023: third-party data breach via Evolve Bank affected Wise customers.",
    details:
      "Wise (formerly TransferWise) is UK-regulated. In 2023, a breach at US partner Evolve Bank exposed personal data for some Wise customers. Wise is generally GDPR-compliant but US operations create data sovereignty concerns.",
    ownerCountry: "GB",
    sellsData: false,
    euAlternativeId: "bunq",
  },
  {
    id: "klarna",
    name: "Klarna",
    domain: "klarna.com",
    category: "finance",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2021 app bug briefly exposed other users' account details.",
    details:
      "In May 2021, a Klarna app bug exposed personal account information of other customers to logged-in users. Swedish fintech regulated by Finansinspektionen and GDPR-compliant.",
    ownerCountry: "SE",
    sellsData: false,
    euAlternativeId: "klarna",
  },
  {
    id: "paypal",
    name: "PayPal",
    domain: "paypal.com",
    category: "finance",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2023 credential stuffing attack exposed 35,000 accounts.",
    details:
      "In January 2023, a credential stuffing attack compromised approximately 35,000 PayPal accounts, exposing names, addresses, Social Security numbers, and transaction history. PayPal is US-based and a frequent target for fraud.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.paypal.com/us/cshelp/article/how-do-i-close-my-paypal-account-help246",
    euAlternativeId: "adyen-mollie",
  },
  {
    id: "monzo",
    name: "Monzo",
    domain: "monzo.com",
    category: "finance",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "Minor incidents; strong security practices and UK FCA regulated.",
    details:
      "Monzo is a UK-regulated digital bank with strong security practices including real-time fraud detection and instant card freezing. Post-Brexit UK regulation means it is outside GDPR, but Monzo maintains strong data practices.",
    ownerCountry: "GB",
    sellsData: false,
    euAlternativeId: "n26",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    domain: "coinbase.com",
    category: "finance",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2024: insider data theft exposed personal info of 69,000 customers.",
    details:
      "In 2024, Coinbase disclosed that rogue employees sold customer data to criminals, including names, addresses, government IDs, and partial bank account numbers for approximately 69,000 customers. US-based and highly targeted by social engineering.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://help.coinbase.com/en/coinbase/privacy-and-security/data-privacy/how-can-i-delete-my-personal-data",
    euAlternativeId: "bitpanda",
  },

  // --- Additional Streaming ---
  {
    id: "hulu",
    name: "Hulu",
    domain: "hulu.com",
    category: "streaming",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "2017 breach exposed subscriber emails; ongoing data-sharing concerns.",
    details:
      "Hulu (owned by Disney) shares viewing data with advertisers and has faced FTC scrutiny. A 2017 breach exposed subscriber email addresses. US-only service subject to US CLOUD Act.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://help.hulu.com/s/article/cancel-account",
  },
  {
    id: "deezer",
    name: "Deezer",
    domain: "deezer.com",
    category: "streaming",
    threatScore: "HIGH",
    dataProtection: "MEDIUM",
    breachSummary: "2022 breach exposed 258M user records on a hacking forum.",
    details:
      "In late 2022, data for 258 million Deezer users was exposed on a hacking forum, including names, birth dates, email addresses, and genders. Despite the breach, Deezer (French company) maintains GDPR compliance practices.",
    ownerCountry: "FR",
    sellsData: false,
    euAlternativeId: "deezer",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    domain: "soundcloud.com",
    category: "streaming",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Acquired by US investors; some data sharing with advertisers.",
    details:
      "SoundCloud was founded in Germany but is now majority-owned by US investors. It collects listening habits, upload metadata, and social connections. No major standalone breaches, but ownership changes have raised data governance concerns.",
    ownerCountry: "DE",
    sellsData: false,
  },
  {
    id: "tidal",
    name: "Tidal",
    domain: "tidal.com",
    category: "streaming",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches. Owned by Block (formerly Square).",
    details:
      "Tidal is a US-based music streaming service owned by Block (Jack Dorsey's company). No significant data breaches reported, but US ownership means it is subject to the CLOUD Act. Focuses on lossless audio quality.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "deezer",
  },
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    domain: "crunchyroll.com",
    category: "streaming",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2020: 1.5M credentials leaked; frequent account takeovers.",
    details:
      "Crunchyroll (owned by Sony/Funimation) suffered a major credential leak in 2020 with approximately 1.5 million accounts compromised. The platform frequently experiences account takeover attacks targeting anime fans.",
    ownerCountry: "US",
    sellsData: false,
  },

  // --- Additional Shopping ---
  {
    id: "aliexpress",
    name: "AliExpress",
    domain: "aliexpress.com",
    category: "shopping",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Chinese parent Alibaba; massive data collection with no GDPR protection.",
    details:
      "AliExpress is owned by Alibaba (China). Chinese law requires tech companies to provide data to Chinese security services on request. No meaningful GDPR protection for EU users. Collects extensive shopping, payment, and behavioural data.",
    ownerCountry: "CN",
    sellsData: true,
    deleteUrl: "https://best.aliexpress.com/account/privacy-center",
  },
  {
    id: "shein",
    name: "Shein",
    domain: "shein.com",
    category: "shopping",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2018 breach exposed 39M accounts; Chinese data law applies.",
    details:
      "Shein suffered a major breach in 2018 affecting approximately 39 million accounts. The company is registered in Singapore but closely tied to China with significant Chinese data law exposure. Multiple GDPR violations in EU.",
    ownerCountry: "SG",
    sellsData: true,
    deleteUrl: "https://www.shein.com/account/privacy/account-deletion",
  },
  {
    id: "temu",
    name: "Temu",
    domain: "temu.com",
    category: "shopping",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2024: 87M records stolen. Aggressive data collection practices.",
    details:
      "Temu (owned by PDD Holdings, China) was found collecting far more data than necessary including device identifiers, location, and network activity. In 2024 a breach exposed 87 million records. Multiple lawsuits and regulatory investigations pending.",
    ownerCountry: "CN",
    sellsData: true,
    deleteUrl: "https://www.temu.com/account/privacy-security",
  },
  {
    id: "etsy",
    name: "Etsy",
    domain: "etsy.com",
    category: "shopping",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Credential stuffing attacks have targeted accounts; US-based.",
    details:
      "Etsy is a US-based marketplace for handmade and vintage goods. Subject to the US CLOUD Act. Has experienced account takeover attempts through credential stuffing. Sells advertising based on browsing and purchase behaviour.",
    ownerCountry: "US",
    sellsData: true,
  },
  {
    id: "zalando",
    name: "Zalando",
    domain: "zalando.com",
    category: "shopping",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches. German-listed, GDPR-compliant.",
    details:
      "Zalando is a German-listed fashion retailer, GDPR-compliant and regulated under EU law. No significant data breaches reported. One of the few major e-commerce platforms fully within EU jurisdiction.",
    ownerCountry: "DE",
    sellsData: false,
    euAlternativeId: "zalando",
  },
  {
    id: "asos",
    name: "ASOS",
    domain: "asos.com",
    category: "shopping",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2020: customer data exposed in third-party breach.",
    details:
      "ASOS (UK) experienced a data exposure in 2020 via a third-party contractor. Post-Brexit UK regulation means no direct GDPR enforcement. Collects extensive browsing, purchase, and size data for personalisation.",
    ownerCountry: "GB",
    sellsData: false,
    euAlternativeId: "zalando",
  },
  {
    id: "vinted",
    name: "Vinted",
    domain: "vinted.com",
    category: "shopping",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches. Lithuanian second-hand fashion marketplace.",
    details:
      "Vinted is a Lithuanian company (Vilnius), fully GDPR-compliant. No significant data breaches reported. One of the largest European fashion resale platforms.",
    ownerCountry: "LT",
    sellsData: false,
    euAlternativeId: "vinted",
  },

  // --- Productivity ---
  {
    id: "notion",
    name: "Notion",
    domain: "notion.so",
    category: "productivity",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "2022: employee account used to access user data; US-based.",
    details:
      "Notion (US) disclosed in 2022 that an employee's account was used to access user data. Notion stores all workspace content in plaintext on US servers, with no zero-knowledge encryption. Subject to the US CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://www.notion.so/help/delete-account",
    euAlternativeId: "cryptpad",
  },
  {
    id: "trello",
    name: "Trello",
    domain: "trello.com",
    category: "productivity",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2024: 15M Trello account profiles scraped and published.",
    details:
      "In January 2024, data from approximately 15 million Trello accounts was scraped via an unauthenticated API endpoint and published on a hacking forum. Trello is owned by Atlassian (US-listed Australian company).",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://support.atlassian.com/trello/docs/deleting-your-atlassian-account/",
    euAlternativeId: "meistertask",
  },
  {
    id: "canva",
    name: "Canva",
    domain: "canva.com",
    category: "productivity",
    threatScore: "HIGH",
    dataProtection: "MEDIUM",
    breachSummary: "2019 breach exposed 139M user records.",
    details:
      "In May 2019, Canva suffered a breach exposing data for approximately 139 million users including usernames, real names, email addresses, and hashed passwords. Australian company (GDPR-adjacent but not EU).",
    ownerCountry: "AU",
    sellsData: false,
    deleteUrl: "https://www.canva.com/help/delete-account/",
    euAlternativeId: "penpot",
  },
  {
    id: "figma",
    name: "Figma",
    domain: "figma.com",
    category: "productivity",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "No major breaches; US-based, all design data stored in plaintext.",
    details:
      "Figma (US) stores all design files on US servers in plaintext with no end-to-end encryption. Adobe attempted to acquire Figma for $20B but the deal was blocked by EU regulators. Subject to the US CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://help.figma.com/hc/en-us/articles/360040328773",
    euAlternativeId: "penpot",
  },
  {
    id: "asana",
    name: "Asana",
    domain: "asana.com",
    category: "productivity",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "No major breaches; US-based project management tool.",
    details:
      "Asana (US) stores all project and task data on US servers. No major data breaches reported, but as a US company it is subject to the CLOUD Act. Collects extensive team activity and project data.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "openproject",
  },

  // --- Fitness & Health ---
  {
    id: "strava",
    name: "Strava",
    domain: "strava.com",
    category: "fitness",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2018: Strava heatmap exposed secret military base locations worldwide.",
    details:
      "In 2018, Strava's global activity heatmap revealed the locations and patrol patterns of soldiers at secret military bases worldwide. Strava collects precise GPS routes, health data, and social connections. US-based.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://support.strava.com/hc/en-us/articles/216919327-Deleting-your-Strava-account",
    euAlternativeId: "komoot",
  },
  {
    id: "myfitnesspal",
    name: "MyFitnessPal",
    domain: "myfitnesspal.com",
    category: "fitness",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2018: 150M accounts breached; health and diet data exposed.",
    details:
      "In March 2018, Under Armour's MyFitnessPal was breached with approximately 150 million accounts compromised, exposing usernames, email addresses, and hashed passwords. Health and calorie tracking data is highly sensitive.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://support.myfitnesspal.com/hc/en-us/articles/360032623531",
  },
  {
    id: "fitbit",
    name: "Fitbit / Google Fit",
    domain: "fitbit.com",
    category: "fitness",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "Acquired by Google; health and sleep data merged into Google's data graph.",
    details:
      "Fitbit was acquired by Google in 2021, allowing Google to merge detailed health metrics (heart rate, sleep patterns, activity) into its advertising data graph. Google has faced EU regulatory scrutiny over this acquisition.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://support.google.com/fitbit/answer/12390952",
  },
  {
    id: "headspace",
    name: "Headspace",
    domain: "headspace.com",
    category: "fitness",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "No major breaches; sensitive mental health data collected.",
    details:
      "Headspace (US) collects sensitive mental health and meditation data. No major data breaches reported, but US jurisdiction means data could be accessed under the CLOUD Act. Merged with Ginger (mental health platform) raising further concerns.",
    ownerCountry: "US",
    sellsData: false,
  },
  {
    id: "garmin",
    name: "Garmin Connect",
    domain: "connect.garmin.com",
    category: "fitness",
    threatScore: "HIGH",
    dataProtection: "MEDIUM",
    breachSummary: "2020 WastedLocker ransomware attack shut down services for 5 days.",
    details:
      "In July 2020, Garmin was hit by the WastedLocker ransomware attack, shutting down all Garmin Connect services for 5 days. Garmin reportedly paid a multi-million dollar ransom. All health and GPS route data is stored on US servers.",
    ownerCountry: "US",
    sellsData: false,
  },

  // --- Education ---
  {
    id: "duolingo",
    name: "Duolingo",
    domain: "duolingo.com",
    category: "education",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2023: 2.6M user accounts scraped and published.",
    details:
      "In January 2023, data from 2.6 million Duolingo accounts was scraped using an exposed API and published on a hacking forum, including real names, email addresses, languages studied, and login activity. US-based with global user base.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://support.duolingo.com/hc/en-us/articles/360043890132",
    euAlternativeId: "babbel",
  },
  {
    id: "coursera",
    name: "Coursera",
    domain: "coursera.org",
    category: "education",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "No major breaches; US-based, FERPA/GDPR compliance partial.",
    details:
      "Coursera (US) collects learning patterns, performance data, and professional information. No major data breaches, but as a US company it is subject to the CLOUD Act. GDPR compliance is partial.",
    ownerCountry: "US",
    sellsData: false,
  },

  // --- Nordic Services ---
  {
    id: "vipps",
    name: "Vipps",
    domain: "vipps.no",
    category: "finance",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches. Norwegian mobile payment platform.",
    details:
      "Vipps is a Norwegian mobile payment and banking platform owned by a consortium of Norwegian banks. Subject to strict Norwegian/EEA financial regulation and GDPR. No significant data breaches reported.",
    ownerCountry: "NO",
    sellsData: false,
    euAlternativeId: "vipps",
  },
  {
    id: "finn-no",
    name: "FINN.no",
    domain: "finn.no",
    category: "shopping",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches. Norway's largest marketplace.",
    details:
      "FINN.no is Norway's largest online marketplace, owned by Schibsted (Norwegian media group). Subject to GDPR. No significant data breaches reported. Stores listings, messaging, and payment data.",
    ownerCountry: "NO",
    sellsData: false,
    euAlternativeId: "finn-no",
  },
  {
    id: "telenor",
    name: "Telenor",
    domain: "telenor.com",
    category: "communication",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major consumer breaches. Norwegian telecom.",
    details:
      "Telenor is a Norwegian state-majority-owned telecommunications company. Subject to GDPR and strict Norwegian telecom regulation. No significant data breaches affecting consumers reported.",
    ownerCountry: "NO",
    sellsData: false,
  },
  {
    id: "dnb",
    name: "DNB Bank",
    domain: "dnb.no",
    category: "finance",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches. Norway's largest bank.",
    details:
      "DNB is Norway's largest bank, partially state-owned and strictly regulated under Norwegian/EEA financial law. GDPR-compliant. No significant consumer data breaches reported.",
    ownerCountry: "NO",
    sellsData: false,
    euAlternativeId: "dnb",
  },
  {
    id: "elkjop",
    name: "Elkjøp / Elgiganten",
    domain: "elkjop.no",
    category: "shopping",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches. Nordic electronics retailer.",
    details:
      "Elkjøp (Elgiganten in Sweden/Denmark) is the largest consumer electronics retailer in the Nordic countries, owned by Currys (UK). Subject to GDPR in all markets. No significant data breaches reported.",
    ownerCountry: "GB",
    sellsData: false,
    euAlternativeId: "elkjop",
  },

  // --- Social (additional) ---
  {
    id: "tumblr",
    name: "Tumblr",
    domain: "tumblr.com",
    category: "social",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2013 breach: 65M+ accounts; sold from Yahoo to Automattic.",
    details:
      "Tumblr suffered a breach in 2013 exposing over 65 million accounts, discovered and disclosed in 2016. The platform has changed ownership multiple times (Yahoo → Verizon → Automattic) with unclear data governance.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://tumblr.com/settings/account/delete",
  },
  {
    id: "quora",
    name: "Quora",
    domain: "quora.com",
    category: "social",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2018: 100M user accounts breached.",
    details:
      "In December 2018, Quora disclosed a data breach affecting approximately 100 million users, exposing names, email addresses, encrypted passwords, and private activity. US-based, subject to CLOUD Act.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://www.quora.com/account/delete",
  },
  {
    id: "bereal",
    name: "BeReal",
    domain: "bere.al",
    category: "social",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "Acquired by French company Voodoo; GDPR applies.",
    details:
      "BeReal was acquired by French mobile developer Voodoo in 2024, bringing it under French/EU jurisdiction and GDPR compliance. Collects precise location data and dual camera images. No major breaches reported.",
    ownerCountry: "FR",
    sellsData: false,
  },
  {
    id: "mastodon",
    name: "Mastodon",
    domain: "mastodon.social",
    category: "social",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "Decentralised; individual server security varies.",
    details:
      "Mastodon is a German non-profit-developed open-source social network. Being decentralised, security depends on the chosen server. The flagship mastodon.social is operated from Germany under GDPR. A genuine European alternative to Twitter/X.",
    ownerCountry: "DE",
    sellsData: false,
    euAlternativeId: "mastodon",
  },

  // --- Dev & Tech ---
  {
    id: "gitlab",
    name: "GitLab",
    domain: "gitlab.com",
    category: "tech",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2024: critical authentication bypass CVE; employee phishing incidents.",
    details:
      "GitLab (US-listed) had a critical authentication bypass vulnerability in 2024 (CVE-2024-45409). Cloud data is US-hosted. Self-hosted option avoids data sovereignty concerns. Widely used in EU public sector.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://docs.gitlab.com/ee/user/profile/account/delete_account.html",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    domain: "digitalocean.com",
    category: "tech",
    threatScore: "MEDIUM",
    dataProtection: "MEDIUM",
    breachSummary: "2020: customer billing info exposed via Mailchimp breach.",
    details:
      "DigitalOcean had customer billing information exposed in 2020 via a breach at their email provider Mailchimp. US-based cloud provider subject to the CLOUD Act, but offers EU datacenter regions.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "hetzner-online",
  },

  // --- Travel ---
  {
    id: "tripadvisor",
    name: "Tripadvisor",
    domain: "tripadvisor.com",
    category: "travel",
    threatScore: "MEDIUM",
    dataProtection: "LOW",
    breachSummary: "2020: subset of member data stolen in security incident.",
    details:
      "TripAdvisor disclosed in 2020 that a subset of member data was accessed without authorisation. US-based and extensively monetises user travel data through advertising partnerships.",
    ownerCountry: "US",
    sellsData: true,
    deleteUrl: "https://www.tripadvisor.com/help/account-deletion",
  },
  {
    id: "skyscanner",
    name: "Skyscanner",
    domain: "skyscanner.com",
    category: "travel",
    threatScore: "LOW",
    dataProtection: "MEDIUM",
    breachSummary: "No major breaches. Scottish company acquired by Ctrip (China).",
    details:
      "Skyscanner was founded in Scotland and is GDPR-registered in the UK, but was acquired by Chinese travel giant Ctrip (now Trip.com) in 2016. Chinese ownership raises data sovereignty concerns despite UK registration.",
    ownerCountry: "CN",
    sellsData: false,
  },
  {
    id: "blablacar",
    name: "BlaBlaCar",
    domain: "blablacar.com",
    category: "travel",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches. French carpooling platform.",
    details:
      "BlaBlaCar is a French company (Paris HQ) and one of Europe's largest carpooling platforms. GDPR-compliant and no significant data breaches reported. A genuine European alternative to US ride-sharing apps.",
    ownerCountry: "FR",
    sellsData: false,
    euAlternativeId: "blablacar",
  },
  {
    id: "flixbus",
    name: "FlixBus",
    domain: "flixbus.com",
    category: "travel",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches. German intercity bus platform.",
    details:
      "FlixBus is a German company (Munich HQ) operating intercity bus services across Europe and the US. GDPR-compliant and no significant data breaches reported. One of Europe's largest transport providers.",
    ownerCountry: "DE",
    sellsData: false,
    euAlternativeId: "flixbus",
  },
  {
    id: "norwegian-air",
    name: "Norwegian Air",
    domain: "norwegian.com",
    category: "travel",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No major breaches. Norwegian low-cost airline.",
    details:
      "Norwegian Air Shuttle is a Norwegian airline subject to GDPR and strict EEA aviation data regulation. Collects booking, payment, and passenger data. No significant data breaches reported.",
    ownerCountry: "NO",
    sellsData: false,
    euAlternativeId: "norwegian-air",
  },

  // --- Security Tools ---
  {
    id: "lastpass",
    name: "LastPass",
    domain: "lastpass.com",
    category: "security",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2022: entire password vault database stolen.",
    details:
      "In August 2022, attackers stole LastPass's entire encrypted password vault database along with customer metadata. The breach is considered catastrophic for a password manager. US-based (LogMeIn/GoTo). Millions of customers affected.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://support.lastpass.com/s/article/how-do-i-delete-my-account",
    euAlternativeId: "proton-pass",
  },
  {
    id: "norton",
    name: "Norton / NortonLifeLock",
    domain: "norton.com",
    category: "security",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2023: credential stuffing attack compromised thousands of Norton accounts.",
    details:
      "In January 2023, NortonLifeLock disclosed a credential-stuffing attack that compromised customer accounts, potentially exposing stored passwords in Norton Password Manager. Gen Digital (US) owns Norton, Avast, and multiple other brands.",
    ownerCountry: "US",
    sellsData: false,
    deleteUrl: "https://support.norton.com/sp/en/us/home/current/solutions/v104433906",
  },
  {
    id: "avast",
    name: "Avast",
    domain: "avast.com",
    category: "security",
    threatScore: "HIGH",
    dataProtection: "LOW",
    breachSummary: "2020: Avast subsidiary Jumpshot sold detailed user browsing data to companies including Google and Pepsi.",
    details:
      "In 2020, it was revealed that Avast's subsidiary Jumpshot had been selling highly detailed browsing data of millions of users to companies including Google, Microsoft, and Pepsi. The subsidiary was shut down following the scandal. Now owned by Gen Digital (US).",
    ownerCountry: "CZ",
    sellsData: true,
    deleteUrl: "https://support.avast.com/en-us/article/Delete-avast-account/",
  },
  {
    id: "bitwarden",
    name: "Bitwarden",
    domain: "bitwarden.com",
    category: "security",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No breaches. Open-source password manager.",
    details:
      "Bitwarden is an open-source password manager with a strong security track record. While US-headquartered, the open-source nature allows independent security audits. Zero-knowledge encryption means even Bitwarden cannot read your passwords. Self-hosting available.",
    ownerCountry: "US",
    sellsData: false,
    euAlternativeId: "vaultwarden",
  },
  {
    id: "protonvpn",
    name: "Proton VPN",
    domain: "protonvpn.com",
    category: "security",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "No breaches. Swiss privacy laws provide strongest protection.",
    details:
      "Proton VPN is operated by Proton AG in Switzerland under some of the world's strongest privacy laws. Open-source clients, verified no-log policy, and independent audits. Swiss law means no mandatory data retention or government backdoors.",
    ownerCountry: "CH",
    sellsData: false,
    euAlternativeId: "proton-vpn",
  },
  {
    id: "mullvad",
    name: "Mullvad VPN",
    domain: "mullvad.net",
    category: "security",
    threatScore: "LOW",
    dataProtection: "HIGH",
    breachSummary: "2023 police raid found zero data — proves no-logs policy.",
    details:
      "In April 2023, Swedish police raided Mullvad's offices but found no usable data, confirming its strict no-logs policy. Mullvad accepts cash and cryptocurrency, requires no email to sign up, and is one of the most privacy-respecting VPNs available.",
    ownerCountry: "SE",
    sellsData: false,
    euAlternativeId: "mullvad",
  },
];
