import "jsr:@supabase/functions-js/edge-runtime.d.ts";

interface ReportData {
  generatedAt: string;
  userEmail?: string;
  services: Array<{
    name: string;
    domain: string;
    threatScore: string;
    dataProtection: string;
    breachSummary: string;
    migrated: boolean;
  }>;
  summary: {
    totalServices: number;
    highThreat: number;
    mediumThreat: number;
    lowThreat: number;
    migratedCount: number;
    progressPct: number;
  };
}

/**
 * Generate PDF from report data
 * Returns base64-encoded PDF that can be downloaded
 */
function generatePDF(data: ReportData): string {
  // Simple HTML-based PDF generation (text-only, no external dependencies)
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Digital Europe Privacy Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
    h1 { color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 10px; }
    h2 { color: #2d4a6e; margin-top: 20px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
    th { background-color: #f5f5f5; font-weight: bold; }
    .summary { background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin: 15px 0; }
    .summary-item { margin: 5px 0; }
    .migrated { color: green; font-weight: bold; }
    .pending { color: orange; }
    .high { color: red; }
    .medium { color: orange; }
    .low { color: green; }
    .footer { margin-top: 30px; font-size: 12px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
  </style>
</head>
<body>
  <h1>Digital Europe - Privacy Report</h1>
  <p><strong>Generated:</strong> ${new Date(data.generatedAt).toLocaleString()}</p>
  ${data.userEmail ? `<p><strong>Email:</strong> ${data.userEmail}</p>` : ""}
  
  <h2>Summary</h2>
  <div class="summary">
    <div class="summary-item"><strong>Total Services:</strong> ${data.summary.totalServices}</div>
    <div class="summary-item"><strong>HIGH Threat:</strong> <span class="high">${data.summary.highThreat}</span></div>
    <div class="summary-item"><strong>MEDIUM Threat:</strong> <span class="medium">${data.summary.mediumThreat}</span></div>
    <div class="summary-item"><strong>LOW Threat:</strong> <span class="low">${data.summary.lowThreat}</span></div>
    <div class="summary-item"><strong>Migration Progress:</strong> ${data.summary.migratedCount}/${data.summary.totalServices} (${data.summary.progressPct}%)</div>
  </div>

  <h2>Service Details</h2>
  <table>
    <thead>
      <tr>
        <th>Service</th>
        <th>Domain</th>
        <th>Threat</th>
        <th>Protection</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${data.services
        .map(
          (s) => `
      <tr>
        <td>${s.name}</td>
        <td>${s.domain}</td>
        <td><span class="${s.threatScore.toLowerCase()}">${s.threatScore}</span></td>
        <td>${s.dataProtection}</td>
        <td><span class="${s.migrated ? "migrated" : "pending"}">${s.migrated ? "✓ Migrated" : "⏳ Pending"}</span></td>
      </tr>
      `,
        )
        .join("")}
    </tbody>
  </table>

  <div class="footer">
    <p><strong>Disclaimer:</strong> Threat scores are based on public breach data, GDPR enforcement actions, and ownership analysis.</p>
    <p>Generated by <strong>digitaleu.me</strong> - European Alternatives to Big Tech</p>
    <p>Visit <strong>https://digitaleu.me</strong> to find privacy-first alternatives to Big Tech services.</p>
  </div>
</body>
</html>
  `;

  // Convert HTML to PDF using simple text encoding
  // For production, consider using a library like jsPDF or html2pdf
  // This is a placeholder that returns a simple PDF
  const pdfBase64 = Buffer.from(html).toString("base64");
  return pdfBase64;
}

Deno.serve(async (req: Request) => {
  // CORS headers
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type",
      },
    });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { "Content-Type": "application/json" },
    });
  }

  try {
    const data = (await req.json()) as ReportData;

    // Validate data structure
    if (!data.services || !Array.isArray(data.services)) {
      return new Response(JSON.stringify({ error: "Invalid report data" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    // Generate PDF (for now, return HTML that can be printed as PDF)
    const htmlContent = generatePDF(data);

    // Return downloadable content
    return new Response(
      JSON.stringify({
        success: true,
        message: "PDF generated successfully",
        downloadUrl: `data:text/html;base64,${htmlContent}`,
      }),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      },
    );
  } catch (err) {
    console.error("Error generating PDF:", err);
    return new Response(
      JSON.stringify({
        success: false,
        error: err instanceof Error ? err.message : "Unknown error",
      }),
      {
        status: 500,
        headers: {
          "Content-Type": "application/json",
          "Access-Control-Allow-Origin": "*",
        },
      },
    );
  }
});
