import type { ServiceInfo } from "@digitaleu/shared";

export interface ReportData {
  generatedAt: string;
  userEmail?: string;
  services: Array<{
    name: string;
    domain: string;
    threatScore: string;
    dataProtection: string;
    breachSummary: string;
    migrated: boolean;
  }>;
  summary: {
    totalServices: number;
    highThreat: number;
    mediumThreat: number;
    lowThreat: number;
    migratedCount: number;
    progressPct: number;
  };
}

/**
 * Prepare report data from services and migration status
 */
export function prepareReportData(
  services: ServiceInfo[],
  migrationStatus: Record<string, "pending" | "migrated">,
  userEmail?: string,
): ReportData {
  const totalServices = services.length;
  const migratedCount = services.filter((s) => migrationStatus[s.id] === "migrated").length;
  const highThreat = services.filter((s) => s.threatScore === "HIGH").length;
  const mediumThreat = services.filter((s) => s.threatScore === "MEDIUM").length;
  const lowThreat = services.filter((s) => s.threatScore === "LOW").length;
  const progressPct = services.length > 0 ? Math.round((migratedCount / services.length) * 100) : 0;

  return {
    generatedAt: new Date().toISOString(),
    userEmail,
    services: services.map((s) => ({
      name: s.name,
      domain: s.domain,
      threatScore: s.threatScore,
      dataProtection: s.dataProtection,
      breachSummary: s.breachSummary,
      migrated: migrationStatus[s.id] === "migrated",
    })),
    summary: {
      totalServices,
      highThreat,
      mediumThreat,
      lowThreat,
      migratedCount,
      progressPct,
    },
  };
}

/**
 * Generate CSV from report data
 */
export function generateCSV(data: ReportData): string {
  const lines: string[] = [];

  // Header
  lines.push("Digital Europe - Privacy Report");
  lines.push(`Generated: ${new Date(data.generatedAt).toLocaleString()}`);
  if (data.userEmail) {
    lines.push(`Email: ${data.userEmail}`);
  }
  lines.push("");

  // Summary section
  lines.push("SUMMARY");
  lines.push(`Total Services,${data.summary.totalServices}`);
  lines.push(`High Threat,${data.summary.highThreat}`);
  lines.push(`Medium Threat,${data.summary.mediumThreat}`);
  lines.push(`Low Threat,${data.summary.lowThreat}`);
  lines.push(`Migrated,${data.summary.migratedCount}/${data.summary.totalServices}`);
  lines.push(`Progress,${data.summary.progressPct}%`);
  lines.push("");

  // Services table
  lines.push("SERVICE_DETAILS");
  lines.push("Name,Domain,Threat Score,Data Protection,Known Issues,Migrated");
  for (const service of data.services) {
    const migrated = service.migrated ? "Yes" : "No";
    // Escape CSV values properly
    const escaped = [
      `"${service.name.replace(/"/g, '""')}"`,
      `"${service.domain}"`,
      service.threatScore,
      service.dataProtection,
      `"${service.breachSummary.replace(/"/g, '""')}"`,
      migrated,
    ];
    lines.push(escaped.join(","));
  }
  lines.push("");
  lines.push("DISCLAIMER");
  lines.push("Threat scores are based on public breach data, GDPR enforcement, and ownership analysis.");
  lines.push("Generated by digitaleu.me - European Alternatives to Big Tech");

  return lines.join("\n");
}

/**
 * Download CSV file
 */
export function downloadCSV(filename: string, csv: string) {
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

/**
 * Request PDF generation from backend
 * (PDF generation is handled via Supabase Edge Function)
 */
export async function requestPDFGeneration(
  data: ReportData,
): Promise<{ success: boolean; url?: string; error?: string }> {
  try {
    const response = await fetch("/functions/v1/generate-report-pdf", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(data),
    });

    if (!response.ok) {
      return { success: false, error: `Server error: ${response.statusText}` };
    }

    const result = (await response.json()) as { downloadUrl?: string };
    return { success: true, url: result.downloadUrl };
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : "Unknown error" };
  }
}
